media:
  input: "assets"
  output: "assets"

content:
  - name: "articles"
    label: "Publish New Report"
    type: "collection"
    path: "*.html"
    exclude:
      - "index.html"
    fields:
      - name: "body"
        label: "Paste Complete Document Text"
        type: "rich-text"
